### ISSUE TITLE
English Description Needs More English

### ISSUE THREAD

**Issue by ArtKarp** [danielftk/PCF_Projects#3]
This might need a bit of updating...  😀

English

bounded boundedDatepicker es un componente personalizado (PCF) creado para permitir a los usuarios de Power Apps usar un selector de fechas con limites configurables haciendo uso del control datePicker de la librería Fluent UI

The controls look great.

One question, on the date picker gif, it shows a dark calendar on the right side is that the same datepicker?  The screens change so fast it is hard to understand what I am watching.

**Comment by danielftk** [comment]
Hi, @ArtKarp Thank you for your comments!!!
Sorry for the Spanglish this is my very first time writing a README.MD file... I will update that... can you spot some typos or something that it's not clear at all? I mean, I'm not a native English speaker and most of my English come from personal practice 😅

Regarding the dark calendar, that was my computer calendar (i use the taskbar at the top screen)... just to show the "dynamic" limit of the dates, as you can see when i take the screenshot was Jun 19 and I set the inputs like this: 

i_mindate: -10 ( today-10 days )
i_maxdate: 10 (today + 10 days)

and in the custom control, we have just enabled the dates between Jun 9 to Jun 29.

Regards.

**Comment by ArtKarp** [comment]
Hi Daniel,

Not a problem.  Glad to be of help.
